language: python

python:
  - "2.7"

branches:
  only:
    - master

install:
  - pip install tox

script:
  - tox

env:
  - TOXENV=pep8
  - TOXENV=py3pep8
  - TOXENV=lint
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=doc
  - TOXENV=sphinx
